# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXHyGkA7A10pif5YBIjwCeEQFI3_X36i
"""

!pip install tensorflow matplotlib scikit-learn seaborn

from google.colab import drive
drive.mount('/content/drive')

import zipfile, os

with zipfile.ZipFile("/content/drive/MyDrive/archive.zip", "r") as z:
    z.extractall("./blur_dataset")

print("Folders:", os.listdir("./blur_dataset"))

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import os

IMG_SIZE = (64, 64) 
BATCH_SIZE = 32
DATA_DIR   = "./blur_dataset"
SEED       = 42

train_datagen = ImageDataGenerator(
    rescale           = 1./255,       
    rotation_range    = 15,           
    horizontal_flip   = True,         
    zoom_range        = 0.1,          
    brightness_range  = [0.8, 1.2],   
    validation_split  = 0.3           
)

test_datagen = ImageDataGenerator(
    rescale = 1./255  
)

train_data = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size  = IMG_SIZE,
    batch_size   = BATCH_SIZE,
    class_mode   = "categorical",
    subset       = "training",
    seed         = SEED
)

val_data = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size  = IMG_SIZE,
    batch_size   = BATCH_SIZE,
    class_mode   = "categorical",
    subset       = "validation",
    seed         = SEED
)

print("Classes:", train_data.class_indices)
print("Train images:", train_data.samples)
print("Val images:  ", val_data.samples)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D, BatchNormalization,
    Flatten, Dense, Dropout
)

model = Sequential([

Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(64, 64, 3)),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')  
])

model.compile(
    optimizer = 'adam',
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

early_stop = EarlyStopping(
    monitor   = 'val_loss',
    patience  = 5,
    restore_best_weights = True
)

history = model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 20,
    callbacks       = [early_stop]
)

print("Training Done!")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam

base_model = MobileNetV2(
    input_shape = (64, 64, 3),
    include_top = False,
    weights     = 'imagenet'
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.3)(x)
output = Dense(3, activation='softmax')(x)

tl_model = Model(inputs=base_model.input, outputs=output)

tl_model.compile(
    optimizer = Adam(learning_rate=0.001),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

tl_model.summary()

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor              = 'val_loss',
    patience             = 5,
    restore_best_weights = True
)

tl_history = tl_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 20,
    callbacks       = [early_stop]
)

print("Training Done!")

base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

tl_model.compile(
    optimizer = Adam(learning_rate=0.0001),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

tl_history2 = tl_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 20,
    callbacks       = [early_stop]
)

print("Fine-tuning Done!")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

IMG_SIZE   = (96, 96)
BATCH_SIZE = 32
DATA_DIR   = "./blur_dataset"

datagen = ImageDataGenerator(
    rescale          = 1./255,
    rotation_range   = 15,
    horizontal_flip  = True,
    zoom_range       = 0.1,
    validation_split = 0.3
)

train_data = datagen.flow_from_directory(
    DATA_DIR, target_size=IMG_SIZE,
    batch_size=BATCH_SIZE, class_mode='categorical',
    subset='training', seed=42
)

val_data = datagen.flow_from_directory(
    DATA_DIR, target_size=IMG_SIZE,
    batch_size=BATCH_SIZE, class_mode='categorical',
    subset='validation', seed=42
)

base_model = MobileNetV2(
    input_shape  = (96, 96, 3),
    include_top  = False,
    weights      = 'imagenet'
)
base_model.trainable = False

x      = base_model.output
x      = GlobalAveragePooling2D()(x)
x      = Dense(128, activation='relu')(x)
x      = Dropout(0.3)(x)
output = Dense(3, activation='softmax')(x)

tl_model = Model(inputs=base_model.input, outputs=output)

tl_model.compile(
    optimizer = Adam(learning_rate=0.001),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_accuracy', patience=5,
    restore_best_weights=True
)

history1 = tl_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 20,
    callbacks       = [early_stop]
)

base_model.trainable = True
for layer in base_model.layers[:-20]:
    layer.trainable = False

tl_model.compile(
    optimizer = Adam(learning_rate=0.00001),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

history2 = tl_model.fit(
    train_data,
    validation_data = val_data,
    epochs          = 20,
    callbacks       = [early_stop]
)

print("Done! Final val_accuracy:", max(history2.history['val_accuracy']))

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history1.history['accuracy'],     label='Train Phase1')
axes[0].plot(history1.history['val_accuracy'], label='Val Phase1')
axes[0].plot(history2.history['accuracy'],     label='Train Phase2')
axes[0].plot(history2.history['val_accuracy'], label='Val Phase2')
axes[0].set_title('Accuracy Curve')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history1.history['loss'],     label='Train Phase1')
axes[1].plot(history1.history['val_loss'], label='Val Phase1')
axes[1].plot(history2.history['loss'],     label='Train Phase2')
axes[1].plot(history2.history['val_loss'], label='Val Phase2')
axes[1].set_title('Loss Curve')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('accuracy_loss_curves.png', dpi=150)
plt.show()

val_data.reset()
y_pred  = tl_model.predict(val_data)
y_pred  = np.argmax(y_pred, axis=1)
y_true  = val_data.classes
classes = list(val_data.class_indices.keys())

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes, yticklabels=classes)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=classes))

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.3)

val_fixed = val_datagen.flow_from_directory(
    DATA_DIR,
    target_size  = (96, 96),
    batch_size   = 32,
    class_mode   = 'categorical',
    subset       = 'validation',
    shuffle      = False,
    seed         = 42
)

val_fixed.reset()
y_pred   = tl_model.predict(val_fixed, verbose=1)
y_pred   = np.argmax(y_pred, axis=1)
y_true   = val_fixed.classes
classes  = list(val_fixed.class_indices.keys())

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes, yticklabels=classes)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=classes))

from google.colab import files
import shutil, os

os.makedirs("results", exist_ok=True)
shutil.copy("confusion_matrix.png",     "results/")
shutil.copy("accuracy_loss_curves.png", "results/")
tl_model.save("results/mobilenet_blur_model.h5")

shutil.make_archive("phase2_results", "zip", "results")
files.download("phase2_results.zip")
print("Done!")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, BatchNormalization, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping
import time

datagen = ImageDataGenerator(rescale=1./255, validation_split=0.3)

train_cnn = datagen.flow_from_directory(
    "./blur_dataset", target_size=(96,96),
    batch_size=32, class_mode='categorical',
    subset='training', seed=42
)

val_cnn = datagen.flow_from_directory(
    "./blur_dataset", target_size=(96,96),
    batch_size=32, class_mode='categorical',
    subset='validation', seed=42
)

cnn_model = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(96,96,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')
])

cnn_model.compile(
    optimizer = 'adam',
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

early_stop = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

start = time.time()
cnn_history = cnn_model.fit(
    train_cnn,
    validation_data = val_cnn,
    epochs          = 20,
    callbacks       = [early_stop]
)
cnn_time = time.time() - start

print(f"\nCNN Training Time: {cnn_time:.0f} seconds")
print(f"CNN Best Val Accuracy: {max(cnn_history.history['val_accuracy']):.4f}")
print(f"CNN Trainable Params: {cnn_model.count_params():,}")

import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(figsize=(10, 4))
ax.axis('off')

table_data = [
    ['Metric', 'CNN from Scratch', 'MobileNetV2 (Transfer Learning)'],
    ['Best Val Accuracy', '34.6%', '62%'],
    ['Training Time', '334 sec', '~400 sec'],
    ['Trainable Parameters', '4,813,763', '164,355'],
    ['Train Accuracy', f"{max(cnn_history.history['accuracy']):.1%}", f"{max(history1.history['accuracy']):.1%}"],
    ['Overfitting', 'High (train 65% vs val 34%)', 'Moderate (train 87% vs val 70%)'],
]

table = ax.table(
    cellText  = table_data[1:],
    colLabels = table_data[0],
    loc       = 'center',
    cellLoc   = 'center'
)
table.auto_set_font_size(False)
table.set_fontsize(11)
table.scale(1.2, 2)

for j in range(3):
    table[0, j].set_facecolor('#2E75B6')
    table[0, j].set_text_props(color='white', fontweight='bold')

for i in range(1, len(table_data)):
    table[i, 2].set_facecolor('#E8F8E8')

plt.title('Model Comparison: CNN from Scratch vs MobileNetV2',
          fontsize=13, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
models  = ['CNN from Scratch', 'MobileNetV2\n(Transfer Learning)']
train_acc = [max(cnn_history.history['accuracy']),
             max(history1.history['accuracy'])]
val_acc   = [max(cnn_history.history['val_accuracy']),
             max(history1.history['val_accuracy'])]

x = np.arange(len(models))
ax.bar(x - 0.2, train_acc, 0.4, label='Train Accuracy', color='steelblue')
ax.bar(x + 0.2, val_acc,   0.4, label='Val Accuracy',   color='darkorange')
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.set_ylabel('Accuracy')
ax.set_title('Train vs Validation Accuracy Comparison')
ax.legend()
ax.grid(axis='y', alpha=0.3)
for i, (t, v) in enumerate(zip(train_acc, val_acc)):
    ax.text(i - 0.2, t + 0.01, f'{t:.1%}', ha='center', fontsize=9)
    ax.text(i + 0.2, v + 0.01, f'{v:.1%}', ha='center', fontsize=9)
plt.tight_layout()
plt.savefig('accuracy_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print("Done!")

from google.colab import files
import shutil, os

os.makedirs("all_results", exist_ok=True)

for f in ["confusion_matrix.png", "accuracy_loss_curves.png",
          "model_comparison.png", "accuracy_comparison.png"]:
    if os.path.exists(f):
        shutil.copy(f, "all_results/")

shutil.make_archive("all_results", "zip", "all_results")
files.download("all_results.zip")
print("Done!")